const PHONE="5512996815665";
const wa=(msg)=>"https://wa.me/"+PHONE+"?text="+encodeURIComponent(msg);
document.querySelectorAll(".wa").forEach(a=>{a.href=wa(a.dataset.msg);a.target="_blank";a.rel="noopener";});
const $=id=>document.getElementById(id);
const vehicleForm=$("vehicleForm"), saved=$("vehicleSaved");
function loadVehicle(){const d=JSON.parse(localStorage.getItem("avanteVehicle")||"null");if(!d)return;$("ownerName").value=d.ownerName||"";$("ownerPhone").value=d.ownerPhone||"";$("vehicleModel").value=d.vehicleModel||"V7 Pró";$("purchaseDate").value=d.purchaseDate||"";$("vehicleId").value=d.vehicleId||"";$("vehicleNotes").value=d.vehicleNotes||"";saved.hidden=false;const m=(d.vehicleModel||"V7 Pró");const short=m.replace(" Pró","").toUpperCase();const ids={vehicleArtModel:short,vehicleProfileModel:m,vehicleProfileOwner:d.ownerName||"—",vehicleProfileDate:d.purchaseDate||"—",vehicleProfileId:d.vehicleId||"Não informado"};Object.entries(ids).forEach(([id,val])=>{const el=$(id);if(el)el.textContent=val;});const title=$("vehicleTitle");if(title)title.textContent=m;}
vehicleForm.addEventListener("submit",e=>{e.preventDefault();const d={ownerName:$("ownerName").value,ownerPhone:$("ownerPhone").value,vehicleModel:$("vehicleModel").value,purchaseDate:$("purchaseDate").value,vehicleId:$("vehicleId").value,vehicleNotes:$("vehicleNotes").value};localStorage.setItem("avanteVehicle",JSON.stringify(d));loadVehicle();saved.scrollIntoView({behavior:"smooth",block:"center"});});
$("clearVehicle").addEventListener("click",()=>{localStorage.removeItem("avanteVehicle");vehicleForm.reset();saved.hidden=true;});loadVehicle();
$("supportForm").addEventListener("submit",e=>{e.preventDefault();const msg=`Olá! Quero abrir um atendimento Avante.\nNome: ${$("supportName").value}\nModelo: ${$("supportModel").value}\nContato: ${$("supportContact").value}\nRelato: ${$("supportIssue").value}`;window.open(wa(msg),"_blank");});
$("reviewForm").addEventListener("submit",e=>{e.preventDefault();const msg=`Olá! Quero solicitar uma revisão Avante.\nNome: ${$("reviewName").value}\nModelo: ${$("reviewModel").value}\nKM aproximada: ${$("reviewKm").value||"não informado"}\nPeríodo: ${$("reviewPeriod").value}\nObservação: ${$("reviewNotes").value||"-"}`;window.open(wa(msg),"_blank");});
$("referralForm").addEventListener("submit",e=>{e.preventDefault();const msg=`Olá! Quero registrar uma indicação no Avante Indica.\nIndicador: ${$("referrerName").value}\nWhatsApp indicador: ${$("referrerPhone").value}\nIndicado: ${$("leadName").value}\nWhatsApp indicado: ${$("leadPhone").value}\nModelo de interesse: ${$("leadModel").value}`;window.open(wa(msg),"_blank");});
let deferredPrompt;const installBtn=$("installBtn");window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false;});installBtn.addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true;});if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
document.querySelectorAll(".wa").forEach(a=>{a.href=wa(a.dataset.msg);a.target="_blank";a.rel="noopener";});
